version: 1.0.0

models:
  - name: fct_orders
    columns:
      - name: date_fk
        test:
          - not_null
          - relationships:
              to: ref('dim_dates')
              field: date_pk
      - name: location_fk
        test:
          - not_null
          - relationships:
              to: ref('dim_locations')
              field: location_pk
      - name: product_fk
        test:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_pk
      - name: shipping_fk
        test:
          - not_null
          - relationship:
              to: ref('dim_shippings')
              field: shippping_pk
      - name: promotion_fk
        test:
          - not_null
          - relationship:
              to: ref('dim_promotions')
              filed: promotion_pk
      - name: order_id
        test:
          - unique
  - name: dim_dates
    columns:
      - name: year
        tests:
          - not_null
      - name: month_number
        tests:
          - not_null
      - name: day_number
        tests:
          - not_null
      - name: month_name
        tests:
          - not_null
      - name: day_name
        tests:
          - not_null
  - name: dim_products
    columns:
      - name: product_pk
        tests:
          - unique
          - not_null
      - name: style
        tests:
          - not_null
      - name: asin
        tests:
          - not_null
  - name: dim_shippings
    columns:
      - name: fulfillment
        tests:
          - accepted_values:
              arguments:
                values: ['Merchant','Fashionable']
      - name: shipping_rate
        tests:
          - accepted_values:
              arguments:
                values: ['Expedited','Standard']
  - name: dim_promotions
    columns:
      - name: sales_channel
        tests:
          - accepted_values:
              arguments:
                values: [ 'Fashionable.in', 'Non-Fashionable' ]